spring.application.name=formulari
# Server port
server.port=${PORT:8080}
# Database configuration
spring.datasource.url=jdbc:sqlite:testdb
#spring.datasource.url=jdbc:h2:mem:testdb
#SQLITE
spring.datasource.driver-class-name=com.dbeaver.jdbc.driver.libsql.LibSqlDriver
spring.datasource.url= ${DB_URL}

#spring.datasource.username= ${DB_USER}

spring.datasource.password= ${DB_TOKEN}

#SQLITE
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

#Aquesta opció útil si vols tenir una copia local --> jdbc:libsql:file:/data/usuari.db?syncUrl=libsql://prova1-anfifus.aws-us-west-2.turso.io
#H2
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Enable H2 console
spring.h2.console.enabled=true
# JPA configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Strategy for creation/update of scheme of data 
spring.datasource.hikari.connection-test-query=SELECT 1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.synonyms=true